import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";
import { ReactNode } from "react";

// These styles apply to every route in the application
import "./global.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  test,
}: {
  children: ReactNode;
  test: ReactNode;
}) {
  return (
    <html>
      <body>
        <header>Root Header</header>
        <nav>
          <ul>
            <li>
              <Link href="/">Home</Link>
            </li>
            <li>
              <Link href="/dashboard/page1">Page1</Link>
            </li>
            <li>
              <Link href="/dashboard/page2">Page2</Link>
            </li>
          </ul>
        </nav>
        <div>{test}</div>

        <main>{children}</main>
      </body>
    </html>
  );
}
